FIXED_LAT = 5000

NUM_NODES = 100
ADV_NID = NUM_NODES - 1
TXN_INTERARRIVAL = 5000*5
MINING_TIME = 60*FIXED_LAT*NUM_NODES
SIM_TIME = 25*(MINING_TIME/NUM_NODES)

ADV_PEER_FRAC = 0.75
ADV_TYPE = "selfish"

# MINING_TIME_OF_NETWORK = MINING_TIME / NUM_NODES